//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ArraySpectrum.rc
//
#define ID_FILE_SAVEAS                  1
#define IDS_RIBBON_CAPTURE              2
#define ID_FILE_CAPTURE_START           3
#define IDS_RIBBON_CALIB                4
#define ID_FILE_SNAP                    5
#define IDS_RIBBON_SHOW_PROPERTIES      6
#define ID_FILE_PIXEL                   7
#define ID_FILE_CAPTURE_STOP            8
#define ID_FILE_WAVELENGTH              9
#define IDS_RIBBON_EXPORT_DATA          10
#define ID_FILE_CALIB                   11
#define ID_FILE_STOP                    12
#define ID_FILE_EXPORT_PIXEL_DATA       13
#define ID_FILE_SHOW_PROPERTIES         14
#define ID_TASK_PANEL                   15
#define ID_GRAPH_CTRL                   16
#define ID_FILE_EXPORT_WL_DATA          17
#define IDS_RIBBON_ABOUT                18
#define ID_INFORMATION_ABOUT            19
#define ID_FILE_CONNECT                 20
#define IDS_RIBBON_COMMUNICATION        21
#define IDS_FILE_DISCONNECT             22
#define IDS_ABOUT_DESCRIPTION_SA165     23
#define IDS_ABOUT_DESCRIPTION           24
#define IDS_RIBBON_DISPLAY_SETTINGS     25
#define IDS_RIBBON_VIEW_DATA            26
#define ID_DISPLAY_SETTINGS             27
#define ID_VIEW_DATA_SHOW               28
#define IDS_RIBBON_LASER                29
#define ID_LASER_SETTINGS               30
#define ID_FILE_RAMANSHIFT              31
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_SMALL_ICONS                 110
#define IDB_WRITELARGE                  111
#define IDB_LARGE_RIBBON_ICONS          111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ArraySpectrumTYPE           130
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define IDR_WINDOWS_MENU                152
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDB_EXPLORER_24                 170
#define IDB_SORT_24                     172
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDB_MENU_IMAGES_24              180
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDB_BITMAP_STOP                 310
#define IDD_SETTINGS                    311
#define IDD_PROPERTIESPANEDLG           312
#define IDD_DATAVIEWDLG                 313
#define IDD_GRAPHVIEWDLG                314
#define IDD_CALIBDATADLG                315
#define IDD_COMMPORTSETTINGS            316
#define IDB_BMP_FLAME_OFF               316
#define IDB_BMP_FLAME_ON                317
#define IDC_CHECK_GAIN                  1000
#define IDC_CHECK_INTEGRATION           1001
#define IDC_CHECK_LINECOUNT             1002
#define IDC_BUTTON_APPLY                1004
#define IDC_EDIT_EXPOSURE_TIME          1006
#define IDC_EDIT_GAIN                   1007
#define IDC_EDIT_LINE_COUNT             1008
#define IDC_CHECK_AVERAGE               1009
#define IDC_CHECK_RSD                   1010
#define IDC_EDIT_LINE_COUNT2            1011
#define IDC_EDIT_OFFSET                 1011
#define IDC_CHECK_SD                    1012
#define IDC_EDIT_PIXEL_NO               1014
#define IDC_EDIT_WL                     1015
#define IDC_BUTTON_ADD                  1016
#define IDC_LIST_CALIB_ENTRIES          1017
#define IDC_BUTTON_REMOVE               1018
#define IDC_STATIC_COEFF_A              1020
#define IDC_STATIC_COEFF_C              1021
#define IDC_STATIC_COEFF_B              1022
#define IDC_STATIC_COEFF_D              1023
#define IDC_BUTTON_CALCULATE            1024
#define IDC_BTN_FLAMMABLE_ON_OFF        1025
#define IDC_STATIC_SET_COMM_PORT        1027
#define IDC_COMBO_PORT_NAMES            1028
#define IDC_BTN_FLAMMABLE_SETTINGS      1029
#define IDC_PEAK_WL_LABEL               1030
#define IDC_EDIT_FLAME_PEAK_WL          1031
#define IDC_STATIC_WAVELENGTH_UNITS     1032
#define IDC_STATIC_FALME_WL_TOL_LIMIT   1033
#define IDC_EDIT_FLAME_PEAK_WL_TOL_LIMITS 1034
#define IDC_STATIC_WAVELENGTH_UNITS2    1035
#define IDC_STATIC_FLAME_THOLD          1036
#define IDC_EDIT_FLAME_THRESHOLD        1037
#define IDC_THRESHOLD_UNITS             1038
#define IDC_SEL_COMPOUND_NAME           1039
#define IDC_STATIC_S_PEAK_WL            1040
#define IDC_EDIT_S_PEAK_WL              1041
#define IDC_STATIC_WAVELENGTH_UNITS3    1042
#define IDC_STATIC_S_PEAK_WL_TOL_LIMIT  1043
#define IDC_EDIT_S_PEAK_WL_TOL_LIMIT    1044
#define IDC_STATIC_WAVELENGTH_UNITS4    1045
#define IDC_S_LEVEL1_THLD_LABEL         1046
#define IDC_EDIT_S_LEVEL_1_THLD         1047
#define IDC_THRESHOLD_UNITS2            1048
#define IDC_S_LEVEL_1_THLD_TOL_LIMIT_LABEL 1049
#define IDC_EDIT_S_LEVEL_1_THLD_TOL_LIMIT 1050
#define IDC_THRESHOLD_UNITS3            1051
#define IDC_S_LEVEL2_THLD_LABEL         1052
#define IDC_EDIT_S_LEVEL_2_THLD         1053
#define IDC_THRESHOLD_UNITS4            1054
#define IDC_S_LEVEL_2_THLD_TOL_LIMIT_LABEL 1055
#define IDC_EDIT_S_LEVEL_2_THLD_TOL_LIMIT 1056
#define IDC_THRESHOLD_UNITS5            1057
#define IDC_S_LEVEL_3_THLD_LABEL        1058
#define IDC_EDIT_S_LEVEL_3_THLD         1059
#define IDC_THRESHOLD_UNITS6            1060
#define IDC_S_LEVEL_3_THLD_TOL_LIMIT_LABEL 1061
#define IDC_EDIT_S_LEVEL_3_THLD_TOL_LIMIT 1062
#define IDC_THRESHOLD_UNITS7            1063
#define IDC_S_LEVEL_4_THLD_LABEL        1064
#define IDC_EDIT_S_LEVEL_4_THLD         1065
#define IDC_THRESHOLD_UNITS8            1066
#define IDC_S_LEVEL_4_THLD_TOL_LIMIT    1067
#define IDC_EDIT_S_LEVEL_4_THLD_TOL_LIMIT 1068
#define IDC_THRESHOLD_UNITS9            1069
#define IDC_S_LEVEL_5_THLD              1070
#define IDC_EDIT_S_LEVEL_5_THLD         1071
#define IDC_S_LEVEL_5_THLD_TOL_LIMIT    1072
#define IDC_EDIT_S_LEVEL_5_THLD_TOL_LIMIT 1073
#define IDC_THRESHOLD_UNITS10           1074
#define IDC_THRESHOLD_UNITS11           1075
#define IDC_S_LEVEL_INDICATOR           1076
#define IDC_BTN_APPLY                   1077
#define IDC_COMPOUND_LABEL              1078
#define IDC_COMBO_COMPOUND_NAMES_COL    1079
#define IDC_SELECT_COMPOUND_LABEL       1080
#define IDC_P_LEVEL_INDICATOR2          1081
#define IDC_AS_LEVEL_INDICATOR3         1082
#define IDC_AS_LEVEL_INDICATOR4         1083
#define IDC_HNO_LEVEL_INDICATOR4        1083
#define IDC_BTN_COMPOUND_SETTINGS       1084
#define IDC_S_LEVEL_LABLE               1085
#define IDC_STATIC_P_LEVEL_LABLE        1086
#define IDC_STATIC_AS_LEVEL_LABLE       1087
#define IDC_STATIC_HNO_LEVEL_LABLE      1088
#define IDC_FLAME_GROUP                 1089
#define IDC_GROUP_COMPOUND              1090
#define IDC_BUTTON1                     1091
#define IDC_BTN_FLAME_APPLY             1091
#define IDC_STATIC_PEAK_VALS            1092
#define ID_WRITE_PASTEASHYPERLINK       32770

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1093
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
